version: '3.7'

services:
  web:
    container_name: definition_extraction_dev
    build:
        context: ./services/web
        dockerfile: Dockerfile
    command: flask run --host=0.0.0.0 --port=5005
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5005:5005
    env_file:
      - ./.env.dev
